### PR TITLE
RFC 473: EventBridge Pipes L2 Construct 

### PR DESCRIPTION
**Pull request by RaphaelManke**
This is a request for comments about EventBridge Pipes L2 Construct See #473 for
additional details. 

Closes: #473

APIs are signed off by @mrgrain 

---

_By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache-2.0 license_

### CODE REVIEW

**Comment by RaphaelManke** [comment]
Hi @mrgrain, @spac3lord did one of you find the time already to review the PR? Is it covering enough or are there things missing. 
As this RFC is still part of the old RFC process, the pending RFC PR blocks the possibility to add an alpha module to the cdk repo. 
I'd personally would love to see this merged prior to Re:Invent, before new maybe new features need to be considered 😅

**Comment by mrgrain** [comment]
Thanks @RaphaelManke Apologies for the delay. I'm happy with this now and are putting it into final comments period.

**Review by mrgrain — DISMISSED** [review]

**Comment by mrgrain** [comment]
@merifyio io update

**Comment by mrgrain** [comment]
@mergifyio update

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
